<script type="text/javascript">
$(document).ready(function(){	
	$("#slider").easySlider({
		auto: true, 
		continuous: true,
		numeric: true
	});
});	
</script>

<div id="header">
    <div class="grid_12">
        <div id="slider">
		<ul>				
			<li><a href="http://templatica.com/preview/30"><img src="<?echo $this->basePath(). '/images/01.jpg'?>" alt="Css Template Preview" /></a></li>
			<li><a href="http://templatica.com/preview/7"><img src="<?echo $this->basePath(). 'images/02.jpg'?>" alt="Css Template Preview" /></a></li>
			<li><a href="http://templatica.com/preview/25"><img src="<?echo $this->basePath(). 'images/03.jpg'?>" alt="Css Template Preview" /></a></li>
			<li><a href="http://templatica.com/preview/26"><img src="<?echo $this->basePath(). 'images/04.jpg'?>" alt="Css Template Preview" /></a></li>
			<li><a href="http://templatica.com/preview/27"><img src="<?echo $this->basePath(). 'images/05.jpg'?>" alt="Css Template Preview" /></a></li>			
		</ul>
	</div>
       
    </div>
    <div class="grid_4" id="feeds-top">
        <p>Feeds</p>
    </div>
    <div class="grid_4" id="feeds">
	<ul id="ticker" class="ticker">

		<li>
			<a href="#">jqBarGraph</a> is jQuery plugin that gives you freedom to easily display your data as graphs. 
		</li>
		<li>
			Learn how to create <a href="#">image gallery in 4 lines of Jquery</a>
		</li>
		<li>

			<a href="#">jqFancyTransitions</a> is easy-to-use jQuery plugin for displaying your photos as slideshow with fancy transition effects.
		</li>
		<li>
			<a href="#">mooBarGraph</a> is AJAX graph plugin for MooTools which support two types of graphs, simple bar and stacked bar graph.
		</li>
                <li>
			<a href="#">O Hilton</a> É o cara mais gay da face da terra!
		</li>
	</ul>
    </div>
</div>

<div class="grid_12">

    <div class="grid_5">
        <h2><?php echo $this->translate('Follow Development') ?></h2>
        <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
    </div>
    
    <div class="grid_5 prefix_1">
        <h2><?php echo $this->translate('Discover Modules') ?></h2>
        <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
   </div>

    <div class="clear"></div>
    
   <div class="grid_5">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
   </div>
   
   <div class="grid_5 prefix_1">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
   </div>
</div>